[package]
name = "pros-graphics"
version = "0.0.1"
edition = "2021"
authors = ["pros-rs"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-graphics-core = "0.4.0"
pros-sys = { version = "0.6.0", path = "../pros-sys" }
snafu = { version = "0.8.0", default-features = false, features = [
    "rust_1_61",
    "unstable-core-error",
] }
